import type { SlideMeta } from "@/types/slide";

// 14장 슬라이드 메타데이터 카탈로그 — 발표 Flow·시간·발표자 배정의 단일 소스
export const SLIDE_META: SlideMeta[] = [
  {
    id: "S01",
    number: 1,
    title: "S-DOT",
    subtitle: "영상이 아닌, 의미를 전송하다",
    presenter: "none",
    duration: "30s",
    steps: 1,
    notes: "표지. 드론 영상 loop 배경 + 타이틀 페이드인. Space로 진행.",
  },
  {
    id: "S02",
    number: 2,
    title: "전장 네트워크가 AI의 가장 큰 장애",
    subtitle: "AI 기술이 아니라 네트워크가 문제다",
    presenter: "instructor",
    duration: "1'00\"",
    steps: 3,
    notes: "교관님 도입. 3개 원형(대역폭/차폐/전자전)이 순차 등장 후 중앙 수렴.",
  },
  {
    id: "S03",
    number: 3,
    title: "Army TIGER 4.0 — 드론·로봇 ↑, 대역폭 ↓",
    subtitle: "고화질 영상 vs 9.6Kbps 전투무선망",
    presenter: "instructor",
    duration: "1'00\"",
    steps: 2,
    notes: "좌: 고화질 스트림(컬러), 우: 끊기는 9.6Kbps(흑백 글리치). Space로 우측 등장.",
  },
  {
    id: "S04",
    number: 4,
    title: "패러다임 전환",
    subtitle: "픽셀이 아닌 의미를",
    presenter: "instructor",
    duration: "1'30\"",
    steps: 2,
    notes: "세리프 대형 타이핑 '영상이 아닌 의미를 전송하다'. 핵심 메시지.",
  },
  {
    id: "S05",
    number: 5,
    title: "S-DOT 3-Layer 개념도",
    subtitle: "Edge · Network · C2",
    presenter: "instructor",
    duration: "1'00\"",
    steps: 3,
    notes: "3개 박스 순차 점등 + 화살표 파이프라인. 교관님 마무리.",
  },
  {
    id: "S06",
    number: 6,
    title: "엣지 AI 시맨틱 변환 프로세스",
    subtitle: "드론 영상 → RDF Triple 실시간 변환",
    presenter: "ceo",
    duration: "1'30\"",
    steps: 2,
    notes: "대표님 시연 시작. 좌 드론 영상 / 우 RDF 타이핑 애니메이션.",
  },
  {
    id: "S07",
    number: 7,
    title: "Before → After",
    subtitle: "815.7 KB → 48 B",
    presenter: "ceo",
    duration: "1'00\"",
    steps: 2,
    notes: "압축 게이지 애니메이션 + 17,401:1 카운트업.",
  },
  {
    id: "S08",
    number: 8,
    title: "KPI 패널",
    subtitle: "9개 포맷 Mode A / B / COSE 비교",
    presenter: "ceo",
    duration: "1'30\"",
    steps: 2,
    notes: "4개 KPI 카드 스태거 등장 (278,383:1 / 74B / 94ms / 100%).",
  },
  {
    id: "S09",
    number: 9,
    title: "Avdiivka Day 1 — 1파 공격",
    subtitle: "04:00Z NAI-STAGING 포구화염 탐지",
    presenter: "ceo",
    duration: "1'30\"",
    steps: 2,
    notes: "핵심 전환. 야간 영상 배경(흑백) + 좌측 텍스트 오버레이.",
  },
  {
    id: "S10",
    number: 10,
    title: "1파 → 2파 반복의 이유",
    subtitle: "러시아 C2 한계 vs 우크라이나 S-DOT",
    presenter: "ceo",
    duration: "1'30\"",
    steps: 2,
    notes: "좌 흑백 러시아 / 우 컬러 우크라이나 split screen.",
  },
  {
    id: "S11",
    number: 11,
    title: "2파 팔란티어 의사결정",
    subtitle: "AI 권고 — Yes / No",
    presenter: "ceo",
    duration: "1'30\"",
    steps: 3,
    notes: "[극적 장면] 흑백→컬러 + DecisionCard 등장 + Yes/No 하이라이트.",
  },
  {
    id: "S12",
    number: 12,
    title: "기존 영상전송 vs S-DOT",
    subtitle: "패러다임 비교",
    presenter: "ceo",
    duration: "1'00\"",
    steps: 1,
    notes: "4행 비교표. 전송대상·방식·대역폭·생존성.",
  },
  {
    id: "S13",
    number: 13,
    title: "한계와 필요성",
    subtitle: "완성이 아닌 필요성을 제안합니다",
    presenter: "ceo",
    duration: "1'00\"",
    steps: 3,
    notes: "3개 gap 카드 순차 등장: 실전장 데이터 · C4I 연동 · KVMF 표준화.",
  },
  {
    id: "S14",
    number: 14,
    title: "지금 만들지 않으면 전장에서 늦는다",
    subtitle: "감사합니다",
    presenter: "ceo",
    duration: "30s",
    steps: 1,
    notes: "마무리. 배경 드론 영상 + 연락처 + QR.",
  },
];
